### ISSUE TITLE
End of line issue on linux via WSL

### ISSUE THREAD

**Issue by jimmyff** [awagege/vscode-build-runner#1]
Hey, this works great when running via Windows however when I run in WSL, I get the following error:

```
/mnt/d/dev/dart/os_cloud_functions/functions/os_cf_ping/
flutter pub run build_runner build --delete-conflicting-outputs
/usr/bin/env: ‘bash\r’: No such file or directory 
exit 127


Terminal will be reused by tasks, press any key to close it.
```

Looks like it's an issue with line breaks?

**Comment by xiankq** [comment]
I am currently using Google Translate to communicate with you.
First of all thank you for your issue. In your current environment, can you run Flutter projects through F5?
