### ISSUE TITLE
wrong pubspec.yaml

### ISSUE THREAD

**Issue by Maatteogekko** [awagege/vscode-build-runner#2]
I have multiple dart projects in the same workspace, and the extension picks up only 2 of the 4 pubspec.yaml files. I have a dependency on build_runner only on 2 projects, but these are not the ones found by the extension.

If you need any detailed info let me know

**Comment by xiankq** [comment]
build_runner In the case of a single project but multiple packages, it is necessary to import it for each package. So you should import build_runner in all pubspec.yaml. and configure separate build.yaml for each package.

**Comment by Maatteogekko** [comment]
that's what I did 🙃

**Comment by Maatteogekko** [comment]
Oh wait I didn't solve my issue 😅

Let me give you more information. This is my file structure:

![image](https://user-images.githubusercontent.com/54111322/139229029-7b406dfb-8efb-4b27-bf6a-fe5e3a192534.png)
---
![image](https://user-images.githubusercontent.com/54111322/139229235-01456841-5a13-48ee-885a-2a3e84114b9c.png)
---
![image](https://user-images.githubusercontent.com/54111322/139229472-a0fe88d5-a00e-4046-a347-f25952eb7327.png)
---
![image](https://user-images.githubusercontent.com/54111322/139229678-5ddab4a0-a80f-4fee-94cb-fc31d3d92f73.png)
---
![image](https://user-images.githubusercontent.com/54111322/139229807-c8ea9f83-d348-49c9-a3ee-94051ef908b8.png)

These are my flutter projects, as you can see only `shared_core` and `spa` have a `build.yaml`, and in fact this is the extension panel:

![image](https://user-images.githubusercontent.com/54111322/139230128-a561d035-65ec-43f9-8785-c214c5dd724a.png)
---
The issue is that when I hover on the files represented inside the extension panel to see their path I get respectively:
- shared_core -> code/ui/pubspec.yaml
- spa -> code/appwrite_functions/does_user_exist/pubspec.yaml

which are clearly the wrong ones! In fact when I start the buld_runner for one of them it complains that build_runner dependency is missing, no surprise since it is the wrong pubspec.

I really like this extension and if this bug is solved it would be perfect for me! ⭐
Please let me know if you need any more info 🙏🏻

**Comment by xiankq** [comment]
I have been able to retrore this bug, but I have no time before, I will start repair in the near future.

**Comment by xiankq** [comment]
I have tried to fix the problem, if there are any problems, you can continue to feedback or create a new issue.

Thanks for your issue. @Maatteogekko
