### ISSUE TITLE
Flutter command from Environment

### ISSUE THREAD

**Issue by viniciusaro** [awagege/vscode-build-runner#3]
Hi, Thanks so much for the plugin!

The project I'm working on is setup with [FVM](https://pub.dev/packages/fvm), witch helps managing Flutter versions across all project contributors. FVM allows forwarding Flutter commands to the current installation using `fvm flutter <command>`. 

It would be really nice if we could setup the with Flutter command that will be used to run `build_runner`. 
I'd like the plugin to run:
```
fvm flutter pub run build_runner build --delete-conflicting-outputs
```
Instead of running:
```
flutter pub run build_runner build --delete-conflicting-outputs
```

Does it make sense to you? Another possibility would be to use the current VSCode Flutter version, instead of a global one.

**Comment by xiankq** [comment]
[2.1.0](https://marketplace.visualstudio.com/items?itemName=Kaiqun.build-runner)

**Comment by chinghoi** [comment]
> [2.1.0](https://marketplace.visualstudio.com/items?itemName=Kaiqun.build-runner)

Thank you for creating the plugin. If only it could be written in readme, I found it here and saw that it supports FVM
